name: Notify cra.orcwg.org repository on Push

on:
  push:
    branches:
      - main

jobs:
  dispatch-to-cra-website:
    runs-on: ubuntu-latest

    steps:
      - name: Send repository dispatch to cra.orcwg.org
        uses: peter-evans/repository-dispatch@v3
        with:
          # Fine-grained PAT for cra.orcwg.org repository
          # Required permissions:
          #   - Repository access: Only cra.orcwg.org
          #   - Contents: Read & Write
          #   - Metadata: Read (auto-selected)
          token: ${{ secrets.WEBSITE_DISPATCH_TOKEN }}

          # Target repository that will build and publish to cra.orcwg.org
          # This workflow triggers a build in cra.orcwg.org which:
          #   1. Pulls latest content from cra-hub
          #   2. Builds the 11ty website
          #   3. Publishes to GitHub Pages
          repository: orcwg/cra.orcwg.org

          # Event type that cra.orcwg.org will listen for
          event-type: cra-hub-update

          # Send commit information to the target repository
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "repository": "${{ github.repository }}", "sender": "${{ github.actor }}", "message": "${{ github.event.head_commit.message }}", "timestamp": "${{ github.event.head_commit.timestamp }}"}'
