name: Notify cra.orcwg.org repository on Push

on:
  push:
    branches:
      - main

jobs:
  dispatch-to-cra-website:
    runs-on: ubuntu-latest

    steps:
      - name: Send repository dispatch to cra.orcwg.org
        run: |
          # Send a repository_dispatch event to trigger the cra.orcwg.org rebuild workflow
          # This uses the GitHub REST API to send a custom webhook event
          #
          # Required secret: WEBSITE_DISPATCH_TOKEN
          # Token configuration:
          #   - Resource owner: orcwg (the organization)
          #   - Repository access: Only cra.orcwg.org
          #   - Permissions:
          #       - Contents: Read & Write (required for repository_dispatch)
          #       - Metadata: Read (auto-selected)
          #
          # The target workflow in cra.orcwg.org will:
          #   1. Pull latest content from cra-hub
          #   2. Build the 11ty website
          #   3. Publish to GitHub Pages at https://cra.orcwg.org
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.WEBSITE_DISPATCH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/orcwg/cra.orcwg.org/dispatches \
            -d '{"event_type":"cra-hub-update"}'
